face_width  : 640            # pixel dimensions
face_height : 480
face_xshift : 0              # centered in screen
face_model  : "Lisa"         # eyelashes

face_skin   : 0xFFFF20       # yellowish head
face_back   : 0x000000       # black backdrop
face_brows  : 0xA04040       # brown eyebrows
face_eyes   : 0x000000       # black eye surrounds
face_iris   : 0x00C000       # dark green eye center 
face_stare  : 0x00E0FF       # light blue for stare
face_mouth  : 0xFF00FF       # magenta mouth 

voice_freq  : 250            # hi female fundamental
voice_infl  : 15             # some inflection
voice_shift : 120            # kid formants (+20%)
voice_slow  : 120            # medium slow
voice_drama : 100            # normal excitability
voice_loud  : 0              # user set volume



